/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frame.java
 *
 * Created on 17-nov-2011, 1.52.48
 */
package albe.gotetris;
import java.awt.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author Alberto
 */
public class Frame extends javax.swing.JFrame {

    /** Creates new form Frame */
    public MyCanvas canvas;
    public Debug debug ;
    public Frame() {
        initComponents();
        canvas = new MyCanvas();
        canvas.setSize(GoTetris.grid.weight+(GoTetris.grid.posSpace*10), GoTetris.grid.height+GoTetris.grid.posSpace);
        this.add(canvas);
        this.pack();
        this.setSize(GoTetris.grid.weight+(GoTetris.grid.posSpace*10)+10, GoTetris.grid.height+GoTetris.grid.posSpace+10);
        //debug = new Debug();
        //debug.setVisible(true);
        this.addKeyListener(new java.awt.event.KeyListener() {

            @Override
            public void keyTyped(KeyEvent e) {
                
            }

            @Override
            public void keyPressed(KeyEvent e) {
                switch(e.getKeyChar()){
                    case 'a': {GoTetris.grid.left();break;}
                    case 'd': {GoTetris.grid.right();break;}
                    case 's': {GoTetris.grid.rotateRight();break;}
                    case 'w': {GoTetris.grid.rotateLeft();break;}
                    case 'z': {
                        while (!GoTetris.grid.getCurrentBlock().isIncastrato()) {
                            try {
                                Thread.sleep(50); 
                            }
                            catch(Exception ex) {
                                
                            }
                            GoTetris.grid.down();
                        }
                        break;
                    }
                }
                System.out.print(GoTetris.grid.getCurrentBlock().getCol());
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
